### ISSUE TITLE
export of exclude list

### ISSUE THREAD

**Issue by Monirzadeh** [RedHotRojo/Dark-Mode-Screen#14]
how can export exclude list or settings for specific website.
where can i get that list?

**Comment by RedHotRojo** [comment]
This has been added in the new version in the options page. You can close this issue if you're satisfied.

**Comment by RedHotRojo** [comment]
No, importing a list may cause bugs for some users since the list will require specific formatting and it is nearly impossible for developers to consider all possibilities when validating input. Some hackers may even be able to socially engineer users into importing malicious lists. If you're satisfied with the export list, please close this issue.
